name: Bump

on:
  workflow_dispatch:

jobs:

  ci:
    uses: ./.github/workflows/ci.yml

  bump:
    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: "${{ secrets.DEPLOY_SSH_KEY }}"
    - run: pip3 install Commitizen==2.27.1

    - run: git config --local user.email "github-actions@users.noreply.github.com"
    - run: git config --local user.name "github-actions"

    - run: cz bump --changelog

    - run: git push
    - run: git push --tags
