name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: go get -v -t -d ./...
    - run: gofmt -s -d .
    - run: go build -v
    - run: go test -test.v -race -cover ./...

  go-mod-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum

  conventional-commits:
    if: github.event_name == 'pull_request' # Only check PRs.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: pip3 install -U Commitizen
    - run: cz check --rev-range origin/${{ github.base_ref }}..HEAD
